### ISSUE TITLE
Multi-platform: Setup preferences in database

### ISSUE THREAD

**Issue by jbonisteel** [ooni/probe-multiplatform#26]
setup preferences

**Comment by aanorbel** [comment]
Here is a high level overview of how the preferences on Probe Android looks like. @sdsantos , do you want to change the structure ?
```yml
# Notifications
notifications_enabled: false
#Test Options
automated_testing_enabled: true
automated_testing_wifionly: true
automated_testing_charging: true
max_runtime_enabled: true
max_runtime: '90'
# Website categories
categoies$:
    SRCH: true
    PORN: true
    COMM: true
    COMT: true
    MMED: true
    HATE: true
    POLR: true
    PUBH: true
    GAME: true
    PROV: true
    HACK: true
    MILX: true
    DATE: true
    ANON: true
    ALDR: true
    GMB: true
    XED: true
    REL: true
    GRP: true
    GOVT: true
    ECON: true
    LGBT: true
    FILE: true
    HOST: true
    HUMR: true
    NEWS: true
    ENV: true
    CULTR: true
    CTRL: true
    IGO: true
# Privacy
upload_results: true
send_crash: true
# Proxy

# Advanced
theme_enabled: false
language_setting: auto
debugLogs: false
warn_vpn_in_use: true

# MISC
deleteUploadedJsons: 1722598146583
isNotificationDialog: 13
first_run: false

```

**Comment by sdsantos** [comment]
They look good. We will need to match keys to ensure everything stays the same. Or do a migration to avoid that snake_case/camelCase incoherence.

Is that `categoies` a typo or is it the actual key?

Maybe categories could be a simple list of categories enabled or disable, instead of a map. But that works too of course.

**Comment by aanorbel** [comment]
I just wanted to indent it. Here is how it actually looks.

```yml
# Notifications
notifications_enabled: false
#Test Options
automated_testing_enabled: true
automated_testing_wifionly: true
automated_testing_charging: true
max_runtime_enabled: true
max_runtime: '90'
# Website categories
    SRCH: true
    PORN: true
    COMM: true
    COMT: true
    MMED: true
    HATE: true
    POLR: true
    PUBH: true
    GAME: true
    PROV: true
    HACK: true
    MILX: true
    DATE: true
    ANON: true
    ALDR: true
    GMB: true
    XED: true
    REL: true
    GRP: true
    GOVT: true
    ECON: true
    LGBT: true
    FILE: true
    HOST: true
    HUMR: true
    NEWS: true
    ENV: true
    CULTR: true
    CTRL: true
    IGO: true
# Privacy
upload_results: true
send_crash: true
# Proxy
proxy_hostname: ''
proxy_port: ''

# Advanced
theme_enabled: false
language_setting: auto
debugLogs: false
warn_vpn_in_use: true

# MISC
deleteUploadedJsons: 1722598146583
isNotificationDialog: 13
first_run: false


# Run Tests
test_signal: false
run_http_invalid_request_line: false
test_facebook_messenger: false
run_dash: false
web_connectivity: true
run_ndt: false
test_psiphon: false
test_tor: false
proxy_protocol: none
test_telegram: false
run_http_header_field_manipulation: false
experimental: false
test_whatsapp: false
${descritor_id}_${testname}

# Autorun
autorun_test_whatsapp: true
autorun_experimental: true
autorun_test_psiphon: true
autorun_test_signal: true
autorun_run_http_invalid_request_line: true
autorun_run_http_header_field_manipulation: true
autorun_run_ndt: true
autorun_test_tor: true
autorun_web_connectivity: true
autorun_test_facebook_messenger: true
autorun_run_dash: true
autorun_test_telegram: true

${descritor_id}_autorun_${testname}
```
